version: '3.8'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: contraseñasegura
      MYSQL_DATABASE: escuela
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - db_network

  cassandra:
    image: cassandra:latest
    environment:
      CASSANDRA_CLUSTER_NAME: "Test Cluster"
    ports:
      - "9042:9042"
    networks:
      - db_network

networks:
  db_network:
    driver: bridge

volumes:
  mysql_data:
